// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectWeb.Data;

namespace ProiectWeb.Migrations
{
    [DbContext(typeof(ProiectWebContext))]
    [Migration("20220107171559_ForeignKeys")]
    partial class ForeignKeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProiectWeb.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nr_tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("ProiectWeb.Models.Comanda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FoodtruckID")
                        .HasColumnType("int");

                    b.Property<decimal>("suma")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("FoodtruckID");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("ProiectWeb.Models.Foodtruck", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Amplasament")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nr_camere")
                        .HasColumnType("int");

                    b.Property<int>("Suprafata")
                        .HasColumnType("int");

                    b.Property<string>("Tip_oferta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Foodtruck");
                });

            modelBuilder.Entity("ProiectWeb.Models.Comanda", b =>
                {
                    b.HasOne("ProiectWeb.Models.Client", null)
                        .WithMany("Comanda")
                        .HasForeignKey("ClientID");

                    b.HasOne("ProiectWeb.Models.Foodtruck", null)
                        .WithMany("Comanda")
                        .HasForeignKey("FoodtruckID");
                });

            modelBuilder.Entity("ProiectWeb.Models.Client", b =>
                {
                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("ProiectWeb.Models.Foodtruck", b =>
                {
                    b.Navigation("Comanda");
                });
#pragma warning restore 612, 618
        }
    }
}
